server:
  port: 8080

spring:
  application:
    name: redis-cache-performance
  
  # 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2 콘솔 활성화 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# 캐시 설정
cache:
  type: redis
  redis:
    time-to-live: 600000  # 10분 (밀리초)
    cache-null-values: false

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# 로깅 설정
logging:
  level:
    com.example.rediscacheperformance: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
